name: Test
on: [push, pull_request]
jobs:
  test-format:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
      with:
        go-version: 1.23.x
    - name: Checkout code
      uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v7
    - name: Format
      run: diff -u <(echo -n) <(gofmt -s -d .)
  test-all:
    strategy:
      matrix:
        go-version: [1.23.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v7
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
    - name: Test
      run: go test ./...
